=== Sven1106/Portia/requestSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON Schema for the RequestSchema",
  "type": "object",
  "required": [
    "projectName",
    "startUrl",
    "isFixedListOfUrls",
    "tasks"
  ],
  "properties": {
    "projectName": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "startUrl": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "isFixedListOfUrls": {
      "type": "boolean"
    },
    "tasks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/task"
      },
      "minItems": 1
    }
  },
  "definitions": {
    "task": {
      "type": "object",
      "required": [
        "taskName",
        "nodes"
      ],
      "properties": {
        "taskName": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          },
          "minItems": 1
        }
      }
    },
    "node": {
      "type": "object",
      "required": [
        "name",
        "type",
        "getMultipleFromPage",
        "isRequired",
        "xpath"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "string",
            "number",
            "boolean",
            "object"
          ]
        },
        "getMultipleFromPage": {
          "type": "boolean"
        },
        "isRequired": {
          "type": "boolean"
        },
        "xpath": {
          "type": "string"
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          },
          "minItems": 1
        }
      },
      "if": {
        "properties": {
          "type": {
            "const": "object"
          }
        }
      },
      "then": {
        "required": [
          "attributes"
        ]
      }
    }
  }
}

=== Sven1106/Portia/CoopRequest.json
{
  "projectName": "Coop",
  "startUrl": "https://opskrifter.coop.dk/sitemap",
  "isFixedListOfUrls": true,
  "tasks": [
    {
      "taskName": "allRecipes",
      "nodes": [
        {
          "name": "recipe",
          "type": "object",
          "getMultipleFromPage": false,
          "isRequired": true,
          "xpath": "//article[@class='recipe']",
          "attributes": [
            {
              "name": "heading",
              "type": "string",
              "getMultipleFromPage": false,
              "isRequired": true,
              "xpath": "./header/div/div[2]/div[1]/div/div[1]/h1"
            },
            {
              "name": "ingredients",
              "type": "string",
              "getMultipleFromPage": true,
              "isRequired": true,
              "xpath": "./div[3]/div/div/section[2]/div[1]/div/div[3]/div/ul/li/span[2]/text()"
            },
            {
              "name": "image",
              "type": "object",
              "getMultipleFromPage": false,
              "isRequired": false,
              "xpath": "./header/div/div[1]/div/img",
              "attributes": [
                {
                  "name": "src",
                  "type": "string",
                  "getMultipleFromPage": false,
                  "isRequired": false,
                  "xpath": "./@src"
                },
                {
                  "name": "alt",
                  "type": "string",
                  "getMultipleFromPage": false,
                  "isRequired": false,
                  "xpath": "./@alt"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
