=== Sven1106/Portia/PortiaLib/requestSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON Schema for the RequestSchema",
  "type": "object",
  "required": [
    "projectId",
    "projectName",
    "domain",
    "startUrls",
    "isFixedListOfUrls",
    "crawlerSchemas"
  ],
  "properties": {
    "projectId": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "projectName": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "domain": {
      "type": "string",
      "pattern": "^(.*)$"
    },
    "startUrls": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^(.*)$"
      }
    },
    "isFixedListOfUrls": {
      "type": "boolean"
    },
    "crawlerSchemas": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/crawlerSchema"
      },
      "minItems": 1
    }
  },
  "definitions": {
    "crawlerSchema": {
      "type": "object",
      "required": [
        "name",
        "nodes"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          },
          "minItems": 1
        }
      }
    },
    "node": {
      "type": "object",
      "required": [
        "name",
        "type",
        "getMultipleFromPage",
        "isRequired",
        "xpath"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [
            "string",
            "number",
            "boolean",
            "object"
          ]
        },
        "getMultipleFromPage": {
          "type": "boolean"
        },
        "isRequired": {
          "type": "boolean"
        },
        "xpath": {
          "type": "string"
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/node"
          },
          "minItems": 1
        }
      },
      "if": {
        "properties": {
          "type": {
            "const": "object"
          }
        }
      },
      "then": {
        "required": [
          "attributes"
        ]
      }
    }
  }
}

=== Sven1106/Portia/AkkaWebcrawler/ArlaRequest.json
{
  "projectId": "0fd5bbc2-36eb-47de-837f-64f56b6e824a",
  "projectName": "Arla",
  "domain": "https://www.arla.dk/",
  "startUrls": [
    "https://www.arla.dk/sitemap.xml?type=Modules.Recipes.Business.SitemapUrlWriter.RecipeSitemapUrlWriter"
  ],
  "isFixedListOfUrls": true,
  "crawlerSchemas": [
    {
      "name": "allRecipes",
      "nodes": [
        {
          "name": "recipe",
          "type": "object",
          "getMultipleFromPage": false,
          "isRequired": true,
          "xpath": "//div[@class='c-recipe']",
          "attributes": [
            {
              "name": "heading",
              "type": "string",
              "getMultipleFromPage": false,
              "isRequired": true,
              "xpath": "./div[1]/div[1]/h1"
            },
            {
              "name": "ingredients",
              "type": "string",
              "getMultipleFromPage": true,
              "isRequired": true,
              "xpath": "./div[2]/div[2]/div/div[2]/div/table/tbody/tr/th"
            },
            {
              "name": "image",
              "type": "object",
              "getMultipleFromPage": false,
              "isRequired": false,
              "xpath": "./div[1]/div[2]/picture/img",
              "attributes": [
                {
                  "name": "src",
                  "type": "string",
                  "getMultipleFromPage": false,
                  "isRequired": false,
                  "xpath": "./@src"
                },
                {
                  "name": "alt",
                  "type": "string",
                  "getMultipleFromPage": false,
                  "isRequired": false,
                  "xpath": "./@alt"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
